Repository sjbarag/brs, pull requests merged in 2019-12, with the labels that each got.

#342 Adding functions into custom component scopes
  src/Error.ts
  src/LexerParser.ts
  src/componentprocessor/index.ts
  src/index.ts
  src/interpreter/Environment.ts
  src/interpreter/index.ts
  test/componentprocessor/componentprocessor.test.js
  test/componentprocessor/resources/baseComponent.xml
  test/componentprocessor/resources/extendedComponent.xml
  test/componentprocessor/resources/scripts/baseComponent.brs
  test/componentprocessor/resources/scripts/extendedComponent.brs
  test/componentprocessor/resources/scripts/utility.brs
  test/e2e/ConditionalCompilation.test.js
  test/e2e/E2ETests.js
  test/e2e/TypeChecking.test.js
  test/e2e/resources/components/AdvancedWidget.xml
  test/e2e/resources/components/BaseWidget.xml
  test/e2e/resources/components/NormalWidget.xml
  test/e2e/resources/components/scripts/AdvancedWidget.brs
  test/e2e/resources/components/scripts/BaseWidget.brs
  test/e2e/resources/components/scripts/NormalWidget.brs
  test/e2e/resources/components/scripts/SupportScript.brs
  test/interpreter/Interpreter.test.js
  test/interpreter/resources/baseComponent.xml
  test/interpreter/resources/extendedComponent.xml
  test/interpreter/resources/scripts/baseComponent.brs
  test/interpreter/resources/scripts/extendedComponent.brs
  test/interpreter/resources/scripts/utility.brs
Labels: enhancement, stdlib

#347 feat(rsg, components): Flatten functions through component inheritence chain
  src/componentprocessor/index.ts
  src/interpreter/index.ts
  src/parser/ComponentScopeResolver.ts
  src/parser/index.ts
  test/componentprocessor/componentprocessor.test.js
  test/e2e/resources/components/scripts/BaseWidget.brs
  test/e2e/resources/components/scripts/NormalWidget.brs
  test/interpreter/Interpreter.test.js
  test/interpreter/resources/scripts/baseComponent.brs
  test/parser/ComponentScopeResolver.test.js
  test/parser/resources/baseComponent.xml
  test/parser/resources/baseComponentTwoScripts.xml
  test/parser/resources/extendedComponent.xml
  test/parser/resources/extendedComponent2.xml
  test/parser/resources/scripts/baseComponent.brs
  test/parser/resources/scripts/extendedComponent.brs
  test/parser/resources/scripts/utilityBase.brs
  test/parser/resources/scripts/utilityExtended.brs
Labels: enhancement, scenegraph, stdlib

#353 chore(deps): Upgrade dependencies & reformat
  src/parser/Parser.ts
  test/preprocessor/Manifest.test.js
  yarn.lock
Labels: build, dependencies

#352 feat(stdlib): Implement GetInterface
  src/brsTypes/BrsInterface.ts
  src/brsTypes/BrsType.ts
  src/brsTypes/components/BrsComponent.ts
  src/brsTypes/components/RoArray.ts
  src/brsTypes/components/RoAssociativeArray.ts
  src/brsTypes/components/RoBoolean.ts
  src/brsTypes/components/RoDateTime.ts
  src/brsTypes/components/RoDouble.ts
  src/brsTypes/components/RoFloat.ts
  src/brsTypes/components/RoInt.ts
  src/brsTypes/components/RoRegex.ts
  src/brsTypes/components/RoSGNode.ts
  src/brsTypes/components/RoString.ts
  src/brsTypes/components/Timespan.ts
  src/brsTypes/index.ts
  src/stdlib/GlobalUtilities.ts
  src/stdlib/Json.ts
  src/stdlib/Type.ts
  src/stdlib/index.ts
  test/brsTypes/BrsInterface.test.js
  test/e2e/StdLib.test.js
  test/e2e/resources/stdlib/global-utilities.brs
  test/parser/controlFlow/__snapshots__/For.test.js.snap
  test/parser/controlFlow/__snapshots__/If.test.js.snap
  test/parser/controlFlow/__snapshots__/While.test.js.snap
  test/parser/expression/__snapshots__/Additive.test.js.snap
  test/parser/expression/__snapshots__/ArrayLiterals.test.js.snap
  test/parser/expression/__snapshots__/AssociativeArrayLiterals.test.js.snap
  test/parser/expression/__snapshots__/Boolean.test.js.snap
  test/parser/expression/__snapshots__/Call.test.js.snap
  test/parser/expression/__snapshots__/Exponential.test.js.snap
  test/parser/expression/__snapshots__/Function.test.js.snap
  test/parser/expression/__snapshots__/Indexing.test.js.snap
  test/parser/expression/__snapshots__/Multiplicative.test.js.snap
  test/parser/expression/__snapshots__/PrefixUnary.test.js.snap
  test/parser/expression/__snapshots__/Primary.test.js.snap
  test/parser/expression/__snapshots__/Relational.test.js.snap
  test/parser/statement/__snapshots__/AssignmentOperators.test.js.snap
  test/parser/statement/__snapshots__/Block.test.js.snap
  test/parser/statement/__snapshots__/Declaration.test.js.snap
  test/parser/statement/__snapshots__/Function.test.js.snap
  test/parser/statement/__snapshots__/Goto.test.js.snap
  test/parser/statement/__snapshots__/Increment.test.js.snap
  test/parser/statement/__snapshots__/LibraryStatement.test.js.snap
  test/parser/statement/__snapshots__/Misc.test.js.snap
  test/parser/statement/__snapshots__/PrintStatement.test.js.snap
  test/parser/statement/__snapshots__/ReturnStatement.test.js.snap
  test/parser/statement/__snapshots__/Set.test.js.snap
  test/parser/statement/__snapshots__/Stop.test.js.snap
  test/preprocessor/__snapshots__/parser.test.js.snap
  test/stdlib/GlobalUtilities.test.js
  test/stdlib/Runtime.test.js
Labels: enhancement, stdlib

#354 fix(rsg): Prevent infinite loop when a node extends an unknown component
  src/componentprocessor/index.ts
  test/componentprocessor/componentprocessor.test.js
  test/componentprocessor/resources/unknownExtensionComponent.xml
Labels: bug, scenegraph
