Repository sjbarag/brs, pull requests merged in 2020-06, with the labels that each got.

#425 Implement global scope references (m.global)
  src/brsTypes/components/RoSGNode.ts
  test/e2e/ComponentGlobal.test.js
  test/e2e/resources/components/MGlobalWidget.xml
  test/e2e/resources/components/MUniversalWidget.xml
  test/e2e/resources/components/componentGlobalUsage.brs
  test/e2e/resources/components/scripts/MGlobalWidget.brs
Labels: enhancement, interpreter, scenegraph

#427 feat(stdlib): implement callFunc
  src/brsTypes/components/RoSGNode.ts
  src/componentprocessor/index.ts
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/CallFuncComponent.xml
  test/e2e/resources/components/scripts/CallFuncComponent.brs
  test/e2e/resources/components/scripts/CallFuncMain.brs
Labels: stdlib

#441 fix(stdlib): escape from value in string replace
  src/brsTypes/components/RoString.ts
  test/brsTypes/components/RoString.test.js
Labels: bug, stdlib

#438 feat(stdlib): add RoSGNodeEvent
  src/brsTypes/components/BrsComponent.ts
  src/brsTypes/components/RoSGNode.ts
  src/brsTypes/components/RoSGNodeEvent.ts
  src/brsTypes/index.ts
  test/brsTypes/components/RoSGNodeEvent.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/FieldChangeComponent.xml
  test/e2e/resources/components/scripts/FieldChangeComponent.brs
  test/e2e/resources/components/scripts/FieldChangeMain.brs
Labels: enhancement, stdlib

#436 feat(stdlib): implement ContentNode
  src/brsTypes/components/BrsComponent.ts
  src/brsTypes/components/ComponentFactory.ts
  src/brsTypes/components/ContentNode.ts
  src/brsTypes/components/RoSGNode.ts
  src/brsTypes/index.ts
  test/brsTypes/components/ContentNode.test.js
  test/brsTypes/components/RoSGNode.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/ComponentsAsChildren.xml
  test/e2e/resources/components/scripts/ContentNode.brs
Labels: enhancement, stdlib

#442 Allow mocking of "unknown" functions
  src/interpreter/Environment.ts
  test/e2e/BrsMock.test.js
  test/e2e/resources/mockFunctions.brs
Labels: enhancement, stdlib

#445 chore(deps): Upgrade dependencies
  package.json
  yarn.lock
Labels: build, dependencies

#446 chore(output): Target ES2017
  tsconfig.json
Labels: build

#449 fix(interp,stdlib): getCallableFunction ignores non-implemented functions
  src/brsTypes/components/RoSGNode.ts
  src/interpreter/index.ts
  test/e2e/resources/components/BaseComponent.xml
Labels: bug, interpreter, scenegraph

#453 feat(build,ci): Automatically publish tagged commits
  .circleci/config.yml
Labels: build
