Repository sjbarag/brs, pull requests merged in 2020-09, with the labels that each got.

#522 fix(interp): Allow return statements in observeField callbacks
  src/Error.ts
  src/brsTypes/components/RoSGNode.ts
  src/interpreter/TypeMismatch.ts
  src/interpreter/index.ts
  src/parser/BlockEndReason.ts
  test/e2e/resources/components/roSGNode.brs
Labels: bug, interpreter

#524 fix(rsg): Return invalid when findNode passed empty string
  src/brsTypes/components/RoSGNode.ts
  test/brsTypes/components/RoSGNode.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/roSGNode.brs
Labels: bug, scenegraph

#521 feat(rsg): Require a host node for observeField
  src/brsTypes/components/RoSGNode.ts
  src/interpreter/Environment.ts
  src/interpreter/index.ts
  test/e2e/BrsComponents.test.js
  test/e2e/BrsMock.test.js
  test/e2e/resources/components/BrsMockComponents.xml
  test/e2e/resources/components/BrsMockFunctions.xml
  test/e2e/resources/components/BrsPartialMockFunctions.xml
  test/e2e/resources/components/field-change/FieldChangeTestbed.xml
  test/e2e/resources/components/field-change/field-change.brs
  test/e2e/resources/components/field-change/main.brs
  test/e2e/resources/components/roSGNode/main.brs
  test/e2e/resources/components/roSGNode/roSGNode.brs
  test/e2e/resources/components/roSGNode/roSGNodeTestbed.xml
  test/e2e/resources/components/scripts/BrsMockComponents.brs
  test/e2e/resources/components/scripts/BrsMockFunctions.brs
  test/e2e/resources/mock-components-main.brs
  test/e2e/resources/mock-functions-main.brs
  test/e2e/resources/partial-mock-functions-main.brs
  test/e2e/resources/reset-mocks.brs
  test/interpreter/Call.test.js
  test/interpreter/Environment.test.js
  test/interpreter/ForEach.test.js
  test/interpreter/FunctionDeclaration.test.js
  test/interpreter/FunctionExpression.test.js
  test/interpreter/Get.test.js
  test/interpreter/InterpreterTests.js
  test/interpreter/Set.test.js
  test/parser/ParserTests.js
Labels: bug, enhancement, scenegraph

#526 feat(rsg): Implement unobserveField
  src/brsTypes/components/RoSGNode.ts
  test/brsTypes/components/RoSGNode.test.js
  test/e2e/Observers.test.js
  test/e2e/resources/observers/components/Observer.brs
  test/e2e/resources/observers/components/Observer.xml
  test/e2e/resources/observers/components/Observer2.xml
  test/e2e/resources/observers/components/UnscopedObserversTestBed.brs
  test/e2e/resources/observers/components/UnscopedObserversTestBed.xml
  test/e2e/resources/observers/unscoped-main.brs
Labels: e2e, enhancement, scenegraph

#528 v0.29.0
  package.json
Labels: enhancement

#529 feat(scenegraph): Implement ifSGNodeField#getFields()
  src/brsTypes/components/RoSGNode.ts
  test/brsTypes/components/RoSGNode.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/roSGNode/roSGNode.brs
Labels: e2e, enhancement, scenegraph

#532 feat(rsg): Added setString method of ifString interface
  src/brsTypes/components/RoString.ts
  test/brsTypes/components/RoString.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/roString.brs
Labels: enhancement

#533 fix(rsg): Adds optional arg to RoString constructor
  src/brsTypes/components/BrsObjects.ts
  src/brsTypes/components/RoString.ts
  test/brsTypes/components/RoString.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/roString.brs
Labels: bug

#536 fix(parser): add else token
  src/parser/Parser.ts
  test/parser/controlFlow/__snapshots__/If.test.js.snap
  test/parser/statement/__snapshots__/Block.test.js.snap
Labels: bug

#531 implement dim statement (#283)
  src/interpreter/index.ts
  src/parser/Parser.ts
  src/parser/Statement.ts
  test/e2e/Syntax.test.js
  test/e2e/resources/dim.brs
  test/interpreter/Dim.test.js
  test/parser/statement/Dim.test.js
Labels: enhancement

#525 feat(coverage): add code coverage collection
  package.json
  src/coverage/CoverageCollector.ts
  src/coverage/FileCoverage.ts
  src/coverage/index.ts
  src/index.ts
  src/interpreter/BrsFunction.ts
  src/interpreter/index.ts
  src/parser/AstNode.ts
  src/parser/Expression.ts
  src/parser/Statement.ts
  test/coverage/CoverageCollector.test.js
  test/coverage/FileCoverage/expressions.test.js
  test/coverage/FileCoverage/statements.test.js
  test/coverage/resources/script1.brs
  test/coverage/resources/scripts/script2.brs
  test/coverage/resources/scripts/script3.brs
  test/e2e/Coverage.test.js
  test/e2e/__snapshots__/Coverage.test.js.snap
  test/e2e/resources/components/coverage/main.brs
  test/parser/ParserTests.js
  yarn.lock
Labels: enhancement

#541 feat(mocks): return a spy from _brs_.mockFunction
  README.md
  src/extensions/mockFunction.ts
  test/e2e/BrsMock.test.js
  test/e2e/resources/components/scripts/BrsMockFunctions.brs
  test/extensions/MockFunction.test.js
Labels: enhancement

#542 fix(test): remove .only from test case
  test/e2e/BrsMock.test.js
Labels: bug

#547 fix(error-handling): Use addError instead of throw
  src/interpreter/index.ts
  test/e2e/Errors.test.js
  test/e2e/resources/components/errors/dotted-get.brs
  test/e2e/resources/components/errors/illegal-index.brs
  test/e2e/resources/components/errors/indexed-get.brs
Labels: bug

#549 feat(components): configurable directories for component search
  bin/cli.js
  src/componentprocessor/index.ts
  src/index.ts
  src/interpreter/index.ts
  test/componentprocessor/componentprocessor.test.js
Labels: enhancement, scenegraph

#551 fix(stdlib): fix callFunc inheritance and arguments bugs
  src/brsTypes/components/RoSGNode.ts
  test/e2e/BrsComponents.test.js
  test/e2e/CallFunc.test.js
  test/e2e/resources/components/CallFuncComponent.xml
  test/e2e/resources/components/call-func/CallFuncParent.xml
  test/e2e/resources/components/call-func/CallFuncTestbed.xml
  test/e2e/resources/components/call-func/scripts/CallFuncParent.brs
  test/e2e/resources/components/call-func/scripts/CallFuncTestbed.brs
  test/e2e/resources/components/call-func/scripts/main.brs
  test/e2e/resources/components/scripts/CallFuncComponent.brs
  test/e2e/resources/components/scripts/CallFuncMain.brs
Labels: bug, stdlib

#544 fix: minor naming collision with eslint/estree spec
  src/parser/Expression.ts
  src/parser/Statement.ts
  test/e2e/__snapshots__/Coverage.test.js.snap
  test/parser/controlFlow/__snapshots__/If.test.js.snap
  test/parser/expression/__snapshots__/AssociativeArrayLiterals.test.js.snap
  test/parser/expression/__snapshots__/Call.test.js.snap
  test/parser/expression/__snapshots__/Function.test.js.snap
  test/parser/statement/__snapshots__/Block.test.js.snap
  test/parser/statement/__snapshots__/Function.test.js.snap
  test/parser/statement/__snapshots__/Goto.test.js.snap
  test/parser/statement/__snapshots__/Increment.test.js.snap
  test/parser/statement/__snapshots__/LibraryStatement.test.js.snap
  test/parser/statement/__snapshots__/Misc.test.js.snap
  test/parser/statement/__snapshots__/ReturnStatement.test.js.snap
  test/parser/statement/__snapshots__/Set.test.js.snap
  test/parser/statement/__snapshots__/Stop.test.js.snap
Labels: bug, parser
