Repository sjbarag/brs, pull requests merged in 2020-05, with the labels that each got.

#407 fix(parser,stdlib) Run errors ignored
  src/extensions/RunInScope.ts
  src/index.ts
  test/extensions/RunInScope.test.js
Labels: bug, parser, stdlib

#405 feat(stdlib): Implement Group Component
  .editorconfig
  README.md
  package.json
  src/brsTypes/components/Group.ts
  src/brsTypes/components/RoSGNode.ts
  src/brsTypes/index.ts
  src/parser/ComponentScopeResolver.ts
  test/brsTypes/components/Group.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/BrsMock.test.js
  test/e2e/resources/components/ExtendedGroup.xml
  test/e2e/resources/components/Group.brs
  test/e2e/resources/components/Group.xml
Labels: enhancement, scenegraph, stdlib

#412 feat(stdlib): Added support for FindMemberFunction
  src/stdlib/GlobalUtilities.ts
  test/e2e/StdLib.test.js
  test/e2e/resources/stdlib/global-utilities.brs
  test/stdlib/GlobalUtilities.test.js
Labels: enhancement, stdlib

#413 feat(stdlib): implement Font component
  src/brsTypes/BrsType.ts
  src/brsTypes/components/ComponentFactory.ts
  src/brsTypes/components/Font.ts
  src/brsTypes/index.ts
  test/brsTypes/components/Font.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/ComponentsAsChildren.xml
  test/e2e/resources/components/Font.brs
Labels: enhancement, scenegraph, stdlib

#414 feat(stdlib): implement Poster component
  src/brsTypes/components/ComponentFactory.ts
  src/brsTypes/components/Poster.ts
  src/brsTypes/index.ts
  test/brsTypes/components/Poster.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/ComponentsAsChildren.xml
  test/e2e/resources/components/Poster.brs
Labels: enhancement, scenegraph, stdlib

#415 feat(stdlib): implement LayoutGroup component
  src/brsTypes/components/ComponentFactory.ts
  src/brsTypes/components/LayoutGroup.ts
  src/brsTypes/index.ts
  test/brsTypes/components/LayoutGroup.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/ComponentsAsChildren.xml
  test/e2e/resources/components/LayoutGroup.brs
Labels: enhancement, scenegraph, stdlib

#421 Change promise rejection to console.error
  src/parser/ComponentScopeResolver.ts
Labels: bug, interpreter, scenegraph
