Repository sjbarag/brs, pull requests merged in 2020-04, with the labels that each got.

#395 Allow invalid returns for signatures that return object
  src/brsTypes/BrsType.ts
  src/brsTypes/components/BrsObjects.ts
  src/brsTypes/components/RoInvalid.ts
  src/brsTypes/index.ts
  test/brsTypes/components/RoInvalid.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/Functions.test.js
  test/e2e/resources/components/roInvalid.brs
  test/e2e/resources/function/return.brs
  test/interpreter/Call.test.js
Labels: bug, interpreter

#394 bug(interp): Allow Float parameters passed into function signatures expecting Double
  src/brsTypes/Callable.ts
  test/brsTypes/Callable.test.js
Labels: bug, interpreter

#396 chore(deps): Update dependencies
  yarn.lock
Labels: dependencies

#393 bug(parse): Capture `EndIf` token when used alongside `else`
  src/parser/Parser.ts
  test/parser/controlFlow/If.test.js
  test/parser/controlFlow/__snapshots__/If.test.js.snap
  test/parser/statement/__snapshots__/Block.test.js.snap
Labels: bug, parser

#400 fix(parser): Parse scripts included in components
  src/index.ts
Labels: bug

#401 feat(stdlib): Implement roSGNode#update second parameter
  src/brsTypes/components/RoSGNode.ts
  test/brsTypes/components/RoSGNode.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/roSGNode.brs
Labels: bug, enhancement, scenegraph, stdlib

#399 Support Mocking Functions
  src/extensions/index.ts
  src/extensions/mockComponent.ts
  src/extensions/mockFunction.ts
  src/interpreter/Environment.ts
  src/stdlib/CreateObject.ts
  test/e2e/BrsMock.test.js
  test/e2e/resources/mockComponents.brs
  test/e2e/resources/mockFunctions.brs
  test/extensions/MockFunction.test.js
  test/interpreter/Environment.test.js
Labels: enhancement, interpreter
