Repository sjbarag/brs, pull requests merged in 2020-08, with the labels that each got.

#488 fix(stdlib): make tests run again
  src/interpreter/Environment.ts
Labels: bug, stdlib

#492 fix(exts,mocks): differentiate between scoped and unscoped function mocks
  src/extensions/mockComponentPartial.ts
  src/interpreter/Environment.ts
  test/e2e/BrsComponents.test.js
  test/e2e/BrsMock.test.js
  test/e2e/resources/components/ComponentMockFunctions.xml
  test/e2e/resources/components/ComponentWithoutMockFunctions.xml
  test/e2e/resources/components/scripts/ComponentMockFunctions.brs
  test/e2e/resources/components/scripts/ComponentWithoutMockFunctions.brs
  test/e2e/resources/components/scripts/MockFunctionsMain.brs
  test/e2e/resources/components/scripts/MockFunctionsUtils-C.brs
Labels: bug, e2e

#493 fix(stdlib): URIs with pkg protocol are scoped to project dir
  src/stdlib/File.ts
  test/stdlib/File.test.js
Labels: bug, stdlib

#487 fix(stdlib): Create nested children correctly
  src/brsTypes/components/RoSGNode.ts
  test/e2e/NestedInlineChildren.test.js
  test/e2e/resources/components/NestedInlineChildren.xml
  test/e2e/resources/components/scripts/NestedInlineChildren.brs
  test/e2e/resources/components/scripts/NestedInlineChildrenMain.brs
Labels: bug, stdlib

#511 fix(rsg): Cast numbers to proper field types
  src/brsTypes/Double.ts
  src/brsTypes/Float.ts
  src/brsTypes/Int32.ts
  src/brsTypes/components/RoSGNode.ts
  test/brsTypes/components/RoSGNode.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/roSGNode.brs
Labels: bug, scenegraph

#509 feat(stdlib): Added case sensitive support to roAssociativeArray
  src/brsTypes/components/RoAssociativeArray.ts
  test/brsTypes/components/RoAssociativeArray.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/roAssociativeArray.brs
Labels: enhancement, stdlib

#512 feat(perf): further memoize lexing and parsing
  src/LexerParser.ts
  src/parser/ComponentScopeResolver.ts
Labels: enhancement, lexer, parser

#507 feat: Make AST compatible with ESLint
  src/parser/AstNode.ts
  src/parser/Expression.ts
  src/parser/Parser.ts
  src/parser/Statement.ts
  test/parser/controlFlow/__snapshots__/For.test.js.snap
  test/parser/controlFlow/__snapshots__/ForEach.test.js.snap
  test/parser/controlFlow/__snapshots__/If.test.js.snap
  test/parser/controlFlow/__snapshots__/While.test.js.snap
  test/parser/expression/__snapshots__/Additive.test.js.snap
  test/parser/expression/__snapshots__/ArrayLiterals.test.js.snap
  test/parser/expression/__snapshots__/AssociativeArrayLiterals.test.js.snap
  test/parser/expression/__snapshots__/Boolean.test.js.snap
  test/parser/expression/__snapshots__/Call.test.js.snap
  test/parser/expression/__snapshots__/Exponential.test.js.snap
  test/parser/expression/__snapshots__/Function.test.js.snap
  test/parser/expression/__snapshots__/Indexing.test.js.snap
  test/parser/expression/__snapshots__/Multiplicative.test.js.snap
  test/parser/expression/__snapshots__/PrefixUnary.test.js.snap
  test/parser/expression/__snapshots__/Primary.test.js.snap
  test/parser/expression/__snapshots__/Relational.test.js.snap
  test/parser/statement/__snapshots__/AssignmentOperators.test.js.snap
  test/parser/statement/__snapshots__/Block.test.js.snap
  test/parser/statement/__snapshots__/Declaration.test.js.snap
  test/parser/statement/__snapshots__/Function.test.js.snap
  test/parser/statement/__snapshots__/Goto.test.js.snap
  test/parser/statement/__snapshots__/Increment.test.js.snap
  test/parser/statement/__snapshots__/LibraryStatement.test.js.snap
  test/parser/statement/__snapshots__/Misc.test.js.snap
  test/parser/statement/__snapshots__/PrintStatement.test.js.snap
  test/parser/statement/__snapshots__/ReturnStatement.test.js.snap
  test/parser/statement/__snapshots__/Set.test.js.snap
  test/parser/statement/__snapshots__/Stop.test.js.snap
Labels: enhancement, parser

#514 fix(parse): Restore nested block parsing
  src/parser/Parser.ts
  test/e2e/Syntax.test.js
  test/e2e/resources/while-loops.brs
  test/parser/controlFlow/While.test.js
  test/parser/controlFlow/__snapshots__/If.test.js.snap
  test/parser/controlFlow/__snapshots__/While.test.js.snap
Labels: bug, parser

#480 Add RoDeviceInfo Interface
  package.json
  src/brsTypes/components/BrsObjects.ts
  src/brsTypes/components/RoDeviceInfo.ts
  src/brsTypes/index.ts
  test/brsTypes/components/RoDeviceInfo.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/roDeviceInfo.brs
  yarn.lock
Labels: enhancement, stdlib

#520 fix: Change inheritance warning to correct names (#519)
  src/parser/ComponentScopeResolver.ts
Labels: bug

#518 feat(rsg): Add Scene Node
  src/brsTypes/components/ComponentFactory.ts
  src/brsTypes/components/Scene.ts
  src/brsTypes/index.ts
  test/brsTypes/components/Scene.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/ExtendedScene.xml
  test/e2e/resources/components/Scene.brs
Labels: enhancement, scenegraph
