Repository sjbarag/brs, pull requests merged in 2020-07, with the labels that each got.

#443 fix(parser): make if statements with 'not' work
  src/parser/Parser.ts
  test/e2e/Syntax.test.js
  test/e2e/resources/conditionals.brs
Labels: bug, parser

#432 fix(rsg): Make types initialize a little better
  src/brsTypes/BrsType.ts
  src/brsTypes/components/RoAssociativeArray.ts
  src/brsTypes/components/RoSGNode.ts
  test/brsTypes/components/ArrayGrid.test.js
  test/brsTypes/components/ContentNode.test.js
  test/brsTypes/components/Font.test.js
  test/brsTypes/components/Group.test.js
  test/brsTypes/components/Label.test.js
  test/brsTypes/components/LayoutGroup.test.js
  test/brsTypes/components/MarkupGrid.test.js
  test/brsTypes/components/Poster.test.js
  test/brsTypes/components/Rectangle.test.js
  test/brsTypes/components/RoSGNode.test.js
  test/brsTypes/components/RoSGNodeEvent.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/scripts/ComponentFields.brs
Labels: bug, scenegraph

#454 fix(test): Fix expected output for Timer components
  test/brsTypes/components/Timer.test.js
Labels: e2e

#462 fix(rsg,mock): Allow mocked components as children of created components
  src/brsTypes/components/RoSGNode.ts
  test/e2e/BrsMock.test.js
  test/e2e/resources/mockComponents.brs
Labels: bug, scenegraph, stdlib

#465 fix(stdlib): remove duplicate extends warning
  src/componentprocessor/index.ts
  src/parser/ComponentScopeResolver.ts
Labels: bug

#459 fix(err): Silence "Something terrible happened" errors
  src/Error.ts
  src/interpreter/index.ts
  test/cli/cli.test.js
  test/cli/resources/errors/syntax-error.brs
  test/cli/resources/errors/uninitialized-object.brs
  test/e2e/BrsComponents.test.js
  test/e2e/BrsMock.test.js
Labels: bug, interpreter

#468 feat(extensions): enable mock resets
  README.md
  src/extensions/index.ts
  src/extensions/resetMocks.ts
  src/interpreter/Environment.ts
  test/e2e/BrsMock.test.js
  test/e2e/resources/components/ResetMocksComponent.xml
  test/e2e/resources/resetMocks.brs
Labels: documentation, enhancement, stdlib

#469 feat(cicd): Set up GitHub Actions for push & pull_request
  .github/workflows/pull-request.yaml
Labels: build, enhancement

#473 chore(ci): Migrate nightly builds to GitHub Actions
  .circleci/config.yml
  .github/workflows/nightly-build.yaml
Labels: build, dependencies

#472 chore(ci): Disable circleci builds for push & pull_request
  .circleci/config.yml
Labels: build, dependencies

#475 fix(nightly): Fix setup-node params to support noninteractive yarn publish
  .github/workflows/nightly-build.yaml
Labels: bug, build

#474 fix(rsg): Support relative paths in <script/> tags
  src/Error.ts
  src/componentprocessor/index.ts
  test/componentprocessor/componentprocessor.test.js
  test/componentprocessor/resources/extendedComponent.xml
Labels: bug, enhancement, scenegraph

#476 fix(ci): Use actions/setup-node to seed auth token in .npmrc
  .github/workflows/nightly-build.yaml
Labels: bug, build

#477 feat(perf): Memoize component scope resolution lexing and parsing
  src/parser/ComponentScopeResolver.ts
  test/parser/ComponentScopeResolver.test.js
Labels: enhancement, lexer, parser, preprocessor, scenegraph

#478 fix(ci): Make nightly builds actually work
  .github/workflows/nightly-build.yaml
Labels: bug, build

#455 feat(stdlib): Add mock component partial
  src/extensions/index.ts
  src/extensions/mockComponentPartial.ts
  src/interpreter/Environment.ts
  test/e2e/BrsComponents.test.js
  test/e2e/BrsMock.test.js
  test/e2e/resources/components/ComponentMockFunctions.xml
  test/e2e/resources/components/ComponentWithoutMockFunctions.xml
  test/e2e/resources/components/scripts/ComponentMockFunctions.brs
  test/e2e/resources/components/scripts/ComponentWithoutMockFunctions.brs
  test/e2e/resources/components/scripts/MockFunctionsMain.brs
  test/e2e/resources/components/scripts/MockFunctionsUtils-A.brs
  test/e2e/resources/components/scripts/MockFunctionsUtils-B.brs
  test/extensions/MockComponentPartial.test.js
Labels: enhancement, stdlib

#479 chore(ci): Publish new releases via GitHub Actions
  .circleci/config.yml
  .github/workflows/release.yaml
Labels: build, enhancement
