Repository sjbarag/brs, pull requests merged in 2021-03, with the labels that each got.

#625 feat(docs): link to docs site
  README.md
  docs/NotImplemented.md
Labels: documentation, enhancement

#626 fix(docs): fix link to docs site
  README.md
Labels: bug

#622 feat(mocks): mockFunction improvements
  src/extensions/mockFunction.ts
  test/e2e/BrsMock.test.js
  test/e2e/resources/components/mocks/functions/main.brs
Labels: e2e, enhancement

#628 add double support to Str() (#581)
  src/stdlib/String.ts
  test/e2e/StdLib.test.js
  test/e2e/resources/stdlib/strings.brs
Labels: bug
