Repository sjbarag/brs, pull requests merged in 2021-06, with the labels that each got.

#654 feat(lex): Emit comments from the lexer
  src/lexer/Lexer.ts
  src/lexer/Token.ts
  test/lexer/Lexer.test.js
Labels: enhancement, lexer

#657 chore(deps): Upgrade to TypeScript 4
  package.json
  src/brsTypes/components/RoDateTime.ts
  yarn.lock
Labels: dependencies

#658 chore(deps): Upgrade most dev dependencies
  src/componentprocessor/index.ts
  src/parser/Parser.ts
  test/lexer/Lexer.test.js
  yarn.lock
Labels: dependencies

#659 fix(interp): allow functions to be typed as objects
  src/brsTypes/coercion.ts
  test/brsTypes/coercion.test.js
Labels: bug, interpreter

#660 fix(stdlib): make RoSGNode#update case insensitive
  src/brsTypes/components/RoSGNode.ts
Labels: bug

#661 fix(lex): Remove spurious console.log for REM-prefixed comments
  src/lexer/Lexer.ts
Labels: bug, lexer

#663 fix(stdlib, interp): fix `RoSGNode#callFunc` argument error reporting
  src/brsTypes/Callable.ts
  src/brsTypes/components/RoSGNode.ts
  src/interpreter/ArgumentMismatch.ts
  src/interpreter/index.ts
  test/e2e/CallFunc.test.js
  test/e2e/resources/components/call-func/CallFuncTestbed.xml
  test/e2e/resources/components/call-func/scripts/CallFuncTestbed.brs
  test/e2e/resources/components/call-func/scripts/throw/no-args.brs
  test/e2e/resources/components/call-func/scripts/throw/wrong-arg-type.brs
Labels: bug, e2e, interpreter, stdlib
