Repository sjbarag/brs, pull requests merged in 2021-01, with the labels that each got.

#584 feat(rsg): Add isSubtype() and parentSubtype() functions to RoSGNode
  src/brsTypes/components/RoSGNode.ts
  test/brsTypes/components/RoSGNode.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/scripts/ExtendedComponent.brs
Labels: enhancement, scenegraph, stdlib

#601 doc: List unsupported BrightScript components, functions, and statements
  README.md
  docs/NotImplemented.md
Labels: documentation, enhancement

#604 fix(stdlib): callFunc should always return a value
  src/brsTypes/components/RoSGNode.ts
Labels: bug, stdlib

#603 feat(execution): create function to execute with scope
  src/index.ts
  test/e2e/createExecuteWithScope.test.js
  test/e2e/resources/execute-with-scope/in-scope.brs
  test/e2e/resources/execute-with-scope/main.brs
  test/e2e/resources/execute-with-scope/main2.brs
Labels: enhancement

#607 doc: Add table of scenegraph node statuses
  docs/NotImplemented.md
Labels: documentation

#599 Adding support for `RoXMLElement`
  src/brsTypes/components/BrsObjects.ts
  src/brsTypes/components/RoXMLElement.ts
  src/brsTypes/index.ts
  test/brsTypes/components/RoXMLElement.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/roXMLElement.brs
Labels: enhancement, help wanted, stdlib

#600 Implement RoLongInteger, cast int to LongInt, float to Double
  src/brsTypes/Callable.ts
  src/brsTypes/Int64.ts
  src/brsTypes/components/BrsObjects.ts
  src/brsTypes/components/RoLongInteger.ts
  src/brsTypes/index.ts
  src/interpreter/index.ts
  test/brsTypes/components/RoLongInteger.test.js
  test/e2e/BrsComponents.test.js
  test/e2e/resources/components/roIntrinsics.brs
  test/interpreter/Variables.test.js
Labels: bug, enhancement, interpreter, stdlib

#583 feat(rsg): Support adding new BrsObjects at Runtime
  src/brsTypes/components/BrsObjects.ts
  src/brsTypes/components/ComponentFactory.ts
  src/brsTypes/index.ts
  src/parser/ComponentScopeResolver.ts
  src/stdlib/CreateObject.ts
  test/brsTypes/components/ComponentFactory.test.js
  test/e2e/CustomComponents.test.js
  test/e2e/customResources/components/ExtendCustom.brs
  test/e2e/customResources/components/ExtendCustom.xml
  test/e2e/customResources/components/extendCustomMain.brs
  test/stdlib/Runtime.test.js
Labels: enhancement, scenegraph, stdlib

#598 fix(stdlib): fix uninitialized type casing
  src/brsTypes/BrsType.ts
  test/e2e/resources/function/scoping.brs
  test/e2e/resources/stdlib/runtime.brs
  test/stdlib/Runtime.test.js
Labels: bug, stdlib

#614 fix(lex): Allow JS object properties as identifiers
  src/lexer/Lexer.ts
  test/lexer/Lexer.test.js
Labels: bug, lexer

#615 fix(parse,interp): Support unary + operator for numbers
  src/interpreter/index.ts
  src/parser/Parser.ts
  test/e2e/Syntax.test.js
  test/e2e/resources/arithmetic.brs
  test/interpreter/Arithmetic.test.js
  test/parser/expression/PrefixUnary.test.js
  test/parser/expression/__snapshots__/PrefixUnary.test.js.snap
Labels: bug, interpreter, parser

#617 fix(lex): Allow explicit double designator on literals > 10 characters
  src/lexer/Lexer.ts
  test/lexer/Lexer.test.js
Labels: bug, lexer

#618 fix(rsg): Ensure hostNode set in <function> implementation
  src/brsTypes/components/RoSGNode.ts
  test/e2e/CallFunc.test.js
  test/e2e/resources/components/call-func/CallFuncTestbed.xml
  test/e2e/resources/components/call-func/scripts/CallFuncTestbed.brs
  test/e2e/resources/components/call-func/scripts/main.brs
Labels: bug, scenegraph
